# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - 4.0

os:
  - linux
  - osx

cache:
  packages: true

notifications:
  email:
    recipients:
      - ben.goldstein@berkeley.edu
    on_success: change
    on_failure: change

script:
  - Rscript ./install_adoak.R
  - R CMD build .
  - R CMD check *tar.gz --as-cran
  - R CMD INSTALL *tar.gz --install-tests
  - Rscript ./run_tests.R
